build:
  version: "3.0"

cards:
  message: "Welcome to loans Service"
  contactDetails:
    name: "Pablo Lucas"
    email: "pablo.lucv@gmail.com"
  onCallSupport:
    - (555) 555-5555
    - (666) 666-6666