build:
  version: "1.0"

cards:
  message: "Welcome to Cards Service"
  contactDetails:
    name: "Pablo Lucas QA LEAD"
    email: "pablo.lucv@gmail.com"
  onCallSupport:
    - (555) 555-5555
    - (666) 666-6666