spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/pablo-lv/microservices-config"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///Users//plucas//Documents//configserver//config"
encrypt:
  key: "553d808c-b1b5-4f1a-a3a6-26ad36e79b09"

server:
  port: 8071